name: stayput7
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: 9.0.2
  geocoding: ^3.0.0
  hive_flutter: ^1.1.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.0.0
  fluttertoast: ^8.2.1
  fl_chart: ^0.68.0
  csv: ^6.0.0
  share_plus: ^10.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sample_data.csv
